# Generated by Django 4.2.7 on 2023-11-04 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(blank=True, max_length=34, null=True, unique=True)),
                ('date', models.DateTimeField()),
                ('from_number', models.CharField(max_length=20, null=True)),
                ('to_number', models.CharField(max_length=20, null=True)),
                ('recording_url', models.CharField(max_length=500, null=True)),
                ('duration', models.CharField(max_length=10, null=True)),
                ('direction', models.CharField(max_length=30, null=True)),
                ('numbers_pressed', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='phone_no',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='contact',
            name='last_call',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20, null=True)),
                ('msg', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('twilio_phone', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='search.phone')),
            ],
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('time_duration', models.IntegerField(default=0)),
                ('twilio_phone', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='search.phone')),
            ],
        ),
    ]
